### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by TripleK2004** [sdaqo/anipy-cli#6]
I have also installed python3-requests from apt 
The Makefile surely has installed it, pip says installed
I dont understand why this error
```
Traceback (most recent call last):
  File "/home/triplek/.git-repos/anipy-cli/main.py", line 2, in <module>
    from src import query, url, play, history, menu
  File "/home/triplek/.git-repos/anipy-cli/src/query.py", line 4, in <module>
    import requests
ImportError: No module named requests
```
Since ani-cli wasnt working i saw the discussion and that led me here, so ig your python script is working ?

**Comment by sdaqo** [comment]
Try pip install requests and try again

**Comment by sdaqo** [comment]
So after more investigation I also stumbled upon this error `ImportError: cannot import name 'requests' from 'pip._vendor' (/usr/lib/python3.9/site-packages/pip/_vendor/__init__.py)` 
After some research I came to this solution: `curl -sS https://bootstrap.pypa.io/get-pip.py | python` and then `pip install requests`.
I dont know why this issue is appearing but yeah that should solve it.

**Comment by TripleK2004** [comment]
> 

![image](https://user-images.githubusercontent.com/76064725/147682531-f660ca1d-5a79-488c-aefc-30906bcc8363.png)
Still doesnt seem to work , same error

**Comment by sdaqo** [comment]
So some things you should try:
do `python3` and `import requests` does this work?
whats the output of `python --version`
output of `which -a python`
output of `pip show requests`
and output of `pip --version`
Thats maybe a little bit to much but I think there are some conflicts going on with the packackges.

**Comment by TripleK2004** [comment]
Actually it was due to the older python version, i resymlinked python to python3.9 and now it works like a charm.

**Comment by sdaqo** [comment]
I thought that would be the case, probably when calling python it uses a older python version like python2 or something, anyways glad it worked!

**Comment by sdaqo** [comment]
> And no download functionality ? or it doesnt work as of now ?
I didn't  implement this yet. I dont know when I'm going to do this but I plan on doing it.
